---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
# 🔹 Active Service (for end users inside cluster)
apiVersion: v1
kind: Service
metadata:
  name: my-app-active
  namespace: demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector: {}   # Rollouts will inject selectors automatically
---
# 🔹 Preview Service (for testing new version inside cluster)
apiVersion: v1
kind: Service
metadata:
  name: my-app-preview
  namespace: demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector: {}   # Rollouts will inject selectors automatically
---
# 🔹 Rollout with Blue/Green strategy
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  namespace: demo
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: my-app-active
      previewService: my-app-preview
      autoPromotionEnabled: false   # requires manual promotion
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: httpd   # 🔹 Blue version
          ports:
            - containerPort: 80
