apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 60 } # pause for analysis/manual judgment
        - setWeight: 50
        - pause: { duration: 60 }
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: nginx:1.25
          ports:
            - containerPort: 80
